# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf6fad22647c44fa36b26ae08d1e70e1d1e35db4f7f272da28482e7bdf40d4a103227f48391c6e716b17dead1a4f5025d9ced6f4e772695e60943f90a755a38f

test:
  secret_key_base: c1c06c9dbbbda82e0e4c8047a0a53fc7c64636acd74284c71883b8551a7fa82e3268375821f60c123ab6740c076d409be4cf3f9a1278008ffea47e31b189c604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
